In [ ]:
import pandas as pd
import numpy as np

dataset=pd.read_csv('cardio_dataset.csv').values

print(dataset,dataset.shape)

[[  1.   48.  236.  ...   1.    0.    1.1]
 [  0.   48.  260.  ...   1.    1.    7. ]
 [  0.   44.  187.  ...   1.    0.    7. ]
 ...
 [  0.   65.  212.  ...   0.    0.   30.6]
 [  0.   66.  184.  ...   0.    0.   23.8]
 [  1.   45.  203.  ...   1.    0.    1. ]] (6644, 8)


In [ ]:
data=dataset[:,0:7]
target=dataset[:,7]
print('data: ',data)
print('target :',target)

data:  [[  1.  48. 236. ...   0.   1.   0.]
 [  0.  48. 260. ...   0.   1.   1.]
 [  0.  44. 187. ...   1.   1.   0.]
 ...
 [  0.  65. 212. ...   1.   0.   0.]
 [  0.  66. 184. ...   0.   0.   0.]
 [  1.  45. 203. ...   0.   1.   0.]]
target : [ 1.1  7.   7.  ... 30.6 23.8  1. ]


In [ ]:
from sklearn.model_selection import train_test_split
train_data,test_data,train_target,test_target=train_test_split(data,target,test_size=0.1)


In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(train_data,train_target)

LinearRegression()

In [ ]:
print('coef: ',model.coef_)
print('a0 :',model.intercept_)

coef:  [-4.84618713  0.72962856  0.02748536 -0.06897645  5.85341602 -5.28173663
 11.03365731]
a0 : -28.081643684760962


In [ ]:
predicted_target=model.predict(test_data)
print('predicted_target :',len(predicted_target))

predicted_target : 665


In [ ]:
print('actual :',test_target[:10])
print('predict:',np.round(predicted_target[:10],1))

actual : [ 6.6  4.7  0.6  0.9 47.5  2.2 17.2  8.5 17.6 22.4]
predict: [16.5  5.2 -4.9 -2.1 30.6  5.6 20.2 13.5 22.8 23.6]


In [ ]:
from sklearn.metrics import r2_score
r2=r2_score(test_target,predicted_target)
print('r2 :',r2)

r2 : 0.7651524569053876


In [ ]:
import joblib
joblib.dump(model,'Heart-risk-reg-model-surya.sav')

['Heart-risk-reg-model-surya.sav']

In [ ]:
from google.colab import files
files.download('Heart-risk-reg-model-surya.sav')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
test_data=[[1,52,200,32,0,2,0]]
predicted_target=model.predict(test_data)
print(predicted_target)

[-2.26079348]
